### USER REGISTER

POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "username": "rolo",
  "email": "rolo@gmail.com",
  "password": "rolo123"
}

### LOGIN USER

POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "rolo@gmail.com",
  "password": "rolo123"
}

### LOGOUT USER
POST http://localhost:3001/api/auth/logout

### PETICIONES DE PRODUCTOS
GET http://localhost:3001/api/products

### POST CREAR PRODUCTOS
POST http://localhost:3001/api/products
Content-Type: application/json

{
  "name": "Taza de Silent Hill 2 Remake",
  "description": "Taza edicion especial de Silent Hill 2 Remake, donde aparecen los la enfermera y el personaje principal edicion unica.",
  "price": 320,
  "stock": 5,
  "imageUrl": "https://res.cloudinary.com/dlcmcab8l/image/upload/v1771270128/ChatGPT_Image_16_feb_2026_01_28_39_p.m._pjmpxo.png"
}

### PUT Actualizar productos
PUT http://localhost:3001/api/products/699372adebacee109e9c1070
Content-Type: application/json

{
  "price": 240
}

### Obtener un producto por ID
GET http://localhost:3001/api/products/699372adebacee109e9c1070

### DELETE Eliminar un producto por su ID
DELETE http://localhost:3001/api/products/69937794635a30699635e8e5

### ADD TO CART
POST http://localhost:3001/api/cart/add
Content-Type: application/json

{
  "userId": "699e1d28a99e0578374ddba9",
  "productId": "69937dfce839573ef8470fe8",
  "quantity": 1
}

### GET CART
GET http://localhost:3001/api/cart/get/699e1d28a99e0578374ddba9

### UPDATE CART
PUT http://localhost:3001/api/cart/update/699e1d28a99e0578374ddba9
Content-Type: application/json

{
  "productId": "699372adebacee109e9c1070",
  "quantity": 3
}